import { ParsedDataset } from '../types/amazon';

export function getDemoDataset(): ParsedDataset {
  // 62 days of commercial data covering July and August 2026 (Month-over-Month)
  const julyDates = Array.from({ length: 31 }, (_, i) => {
    const day = String(i + 1).padStart(2, '0');
    return `2026-07-${day}`;
  });

  const augustDates = Array.from({ length: 31 }, (_, i) => {
    const day = String(i + 1).padStart(2, '0');
    return `2026-08-${day}`;
  });

  const dates = [...julyDates, ...augustDates];

  const businessDays = dates.map((date, idx) => {
    // July is slightly earlier in store ramp-up, August has higher revenue (+12% MoM)
    const isJuly = date.startsWith('2026-07');
    const isWeekend = idx % 7 === 5 || idx % 7 === 6;
    const baseSales = isJuly ? (isWeekend ? 3400 : 4800) : (isWeekend ? 3900 : 5500);
    const noise = Math.sin(idx) * 800;
    const sales = Math.round(baseSales + noise);
    const units = Math.round(sales / 88);
    const sessions = Math.round(units * 14.5 + Math.random() * 80);
    const orders = Math.round(units * 0.92);

    return {
      date,
      orderedProductSales: sales,
      unitsOrdered: units,
      totalOrderItems: orders,
      sessions,
      pageViews: Math.round(sessions * 1.6),
      buyBoxPercentage: 92.5 + Math.sin(idx) * 4,
      unitSessionPercentage: Number(((units / sessions) * 100).toFixed(2)),
    };
  });

  // Business SKUs
  const businessSkus = [
    {
      sku: 'SKU-CAFE-ESPR-1KG',
      asin: 'B08ABC1234',
      title: 'Café Especial em Grãos Torrado 1kg Gourmet 100% Arábica Cerrado Mineiro',
      sessions: 4250,
      pageViews: 6890,
      buyBoxPercentage: 98.2,
      unitsOrdered: 460,
      orderedProductSales: 41354.0,
      unitSessionPercentage: 10.82,
    },
    {
      sku: 'SKU-MOED-ELETR-INOX',
      asin: 'B08XYZ5678',
      title: 'Moedor de Café Elétrico Automático Lâminas Inox 220V Bivolt Compacto',
      sessions: 3120,
      pageViews: 5410,
      buyBoxPercentage: 94.0,
      unitsOrdered: 185,
      orderedProductSales: 35150.0,
      unitSessionPercentage: 5.93,
    },
    {
      sku: 'SKU-PREN-FRANC-800ML',
      asin: 'B09KLM9012',
      title: 'Prensa Francesa Cafeteira de Vidro Borossilicato 800ml com Filtro Duplo',
      sessions: 2450,
      pageViews: 3820,
      buyBoxPercentage: 96.5,
      unitsOrdered: 210,
      orderedProductSales: 25179.0,
      unitSessionPercentage: 8.57,
    },
    {
      sku: 'SKU-CANEC-TERM-450ML',
      asin: 'B09QWE3456',
      title: 'Caneca Térmica Inox com Tampa Hermética 450ml Parede Dupla Vácuo',
      sessions: 1980,
      pageViews: 2950,
      buyBoxPercentage: 89.1,
      unitsOrdered: 140,
      orderedProductSales: 11186.0,
      unitSessionPercentage: 7.07,
    },
    {
      sku: 'SKU-FILTR-PAPEL-103',
      asin: 'B09RTY7890',
      title: 'Kit 4 Caixas Filtro de Papel para Café N° 103 Orgânico Biodegradável',
      sessions: 1820,
      pageViews: 2310,
      buyBoxPercentage: 99.4,
      unitsOrdered: 320,
      orderedProductSales: 11200.0,
      unitSessionPercentage: 17.58,
    },
    {
      sku: 'SKU-XIC-CERAM-SET4',
      asin: 'B09UIO2345',
      title: 'Conjunto 4 Xícaras de Café Expresso Cerâmica Artesanal 80ml',
      sessions: 1650,
      pageViews: 2200,
      buyBoxPercentage: 79.5,
      unitsOrdered: 45,
      orderedProductSales: 4045.5,
      unitSessionPercentage: 2.73,
    },
    {
      sku: 'SKU-CHAL-ELETR-BCO',
      asin: 'B09PAS6789',
      title: 'Chaleira Elétrica com Termômetro Digital e Controle de Temperatura 1.7L',
      sessions: 2100,
      pageViews: 3450,
      buyBoxPercentage: 91.0,
      unitsOrdered: 32,
      orderedProductSales: 9280.0,
      unitSessionPercentage: 1.52,
    },
  ];

  // All Orders
  const orders: any[] = [];
  let orderCounter = 1000;
  for (let i = 0; i < 280; i++) {
    const month = i < 140 ? '07' : '08';
    const day = String((i % 28) + 1).padStart(2, '0');
    const orderId = `701-492${orderCounter++}-${i * 3 + 1204}`;
    const skuObj = businessSkus[i % businessSkus.length];
    const isShipped = i % 10 !== 0 && i % 25 !== 0;
    const isPending = i % 25 === 0;
    const isCanceled = i % 10 === 0 && !isPending;

    orders.push({
      amazonOrderId: orderId,
      orderItemId: `${orderId}-01`,
      purchaseDate: `2026-${month}-${day}T14:32:00-03:00`,
      lastUpdatedDate: `2026-${month}-${day}T18:00:00-03:00`,
      orderStatus: isShipped ? 'Shipped' : isPending ? 'Pending' : 'Canceled',
      fulfillmentChannel: i % 3 === 0 ? 'Amazon' : 'Merchant',
      salesChannel: 'Amazon.com.br',
      sku: skuObj.sku,
      asin: skuObj.asin,
      productName: skuObj.title,
      quantity: (i % 5 === 0 ? 2 : 1),
      itemPrice: Math.round(skuObj.orderedProductSales / skuObj.unitsOrdered),
      itemTax: 0,
      shippingPrice: i % 3 === 0 ? 0 : 18.9,
      shippingTax: 0,
      itemPromoDiscount: 0,
      shipCity: ['São Paulo', 'Curitiba', 'Belo Horizonte', 'Rio de Janeiro', 'Porto Alegre', 'Salvador'][i % 6],
      shipState: ['SP', 'PR', 'MG', 'RJ', 'RS', 'BA'][i % 6],
      isBusinessOrder: i % 8 === 0,
    });
  }

  // Campaigns
  const campaigns = [
    {
      campaignName: 'SP - Brand Defense - Café Especial',
      status: 'ENABLED',
      budget: 80.0,
      impressions: 48500,
      clicks: 820,
      spend: 984.0,
      orders: 145,
      sales: 13050.0,
      ctr: 1.69,
      cpc: 1.2,
      acos: 7.54,
      roas: 13.26,
    },
    {
      campaignName: 'SP - Categoria - Moedores de Café',
      status: 'ENABLED',
      budget: 150.0,
      impressions: 89400,
      clicks: 1240,
      spend: 2976.0,
      orders: 88,
      sales: 16720.0,
      ctr: 1.39,
      cpc: 2.4,
      acos: 17.8,
      roas: 5.62,
    },
    {
      campaignName: 'SP - Genérica - Café Grãos & Prensa',
      status: 'ENABLED',
      budget: 200.0,
      impressions: 142000,
      clicks: 1980,
      spend: 4158.0,
      orders: 95,
      sales: 11400.0,
      ctr: 1.39,
      cpc: 2.1,
      acos: 36.47,
      roas: 2.74,
    },
    {
      campaignName: 'SP - Concorrentes Diretos - Cafeteiras',
      status: 'ENABLED',
      budget: 120.0,
      impressions: 64200,
      clicks: 850,
      spend: 2465.0,
      orders: 42,
      sales: 5880.0,
      ctr: 1.32,
      cpc: 2.9,
      acos: 41.92,
      roas: 2.39,
    },
    {
      campaignName: 'SB - Marca & Loja - Cafeteria Completa',
      status: 'ENABLED',
      budget: 100.0,
      impressions: 54000,
      clicks: 710,
      spend: 1775.0,
      orders: 68,
      sales: 8160.0,
      ctr: 1.31,
      cpc: 2.5,
      acos: 21.75,
      roas: 4.6,
    },
    {
      campaignName: 'SD - Retargeting Vistas de Produto',
      status: 'PAUSED',
      budget: 60.0,
      impressions: 21000,
      clicks: 220,
      spend: 616.0,
      orders: 14,
      sales: 1680.0,
      ctr: 1.05,
      cpc: 2.8,
      acos: 36.67,
      roas: 2.73,
    },
  ];

  // Search Terms (Includes 10-15 click zero sales keywords for investigation!)
  const searchTerms = [
    {
      campaignName: 'SP - Brand Defense - Café Especial',
      adGroupName: 'Exata - Marca',
      customerSearchTerm: 'cafe especial cerrado gourmet',
      targeting: 'cafe especial cerrado',
      matchType: 'EXACT',
      impressions: 12400,
      clicks: 340,
      spend: 374.0,
      orders: 78,
      sales: 7020.0,
      ctr: 2.74,
      cpc: 1.1,
      acos: 5.33,
      roas: 18.77,
      conversionRate: 22.94,
    },
    {
      campaignName: 'SP - Categoria - Moedores de Café',
      adGroupName: 'Moedor Eletrico',
      customerSearchTerm: 'moedor de cafe eletrico 220v',
      targeting: 'moedor de cafe eletrico',
      matchType: 'PHRASE',
      impressions: 18500,
      clicks: 410,
      spend: 943.0,
      orders: 46,
      sales: 8740.0,
      ctr: 2.22,
      cpc: 2.3,
      acos: 10.79,
      roas: 9.27,
      conversionRate: 11.22,
    },
    // Gasto sob investigação: 10-15 cliques e 0 vendas
    {
      campaignName: 'SP - Genérica - Café Grãos & Prensa',
      adGroupName: 'Generico Cafe',
      customerSearchTerm: 'maquina de espresso profissional expresso bar',
      targeting: 'cafe graos',
      matchType: 'BROAD',
      impressions: 8900,
      clicks: 24,
      spend: 67.2,
      orders: 0,
      sales: 0,
      ctr: 0.27,
      cpc: 2.8,
      acos: 0,
      roas: 0,
      conversionRate: 0,
    },
    {
      campaignName: 'SP - Genérica - Café Grãos & Prensa',
      adGroupName: 'Generico Cafe',
      customerSearchTerm: 'cafe soluvel nescafe lata atacado',
      targeting: 'cafe graos',
      matchType: 'BROAD',
      impressions: 11200,
      clicks: 18,
      spend: 41.4,
      orders: 0,
      sales: 0,
      ctr: 0.16,
      cpc: 2.3,
      acos: 0,
      roas: 0,
      conversionRate: 0,
    },
    {
      campaignName: 'SP - Concorrentes Diretos - Cafeteiras',
      adGroupName: 'Concorrentes',
      customerSearchTerm: 'assistencia tecnica oster cafeteira pecas',
      targeting: 'cafeteira eletrica',
      matchType: 'BROAD',
      impressions: 6400,
      clicks: 15,
      spend: 49.5,
      orders: 0,
      sales: 0,
      ctr: 0.23,
      cpc: 3.3,
      acos: 0,
      roas: 0,
      conversionRate: 0,
    },
    {
      campaignName: 'SP - Concorrentes Diretos - Cafeteiras',
      adGroupName: 'Concorrentes',
      customerSearchTerm: 'cafeteira dolce gusto capsula barata',
      targeting: 'prensa francesa',
      matchType: 'BROAD',
      impressions: 14200,
      clicks: 29,
      spend: 89.9,
      orders: 0,
      sales: 0,
      ctr: 0.2,
      cpc: 3.1,
      acos: 0,
      roas: 0,
      conversionRate: 0,
    },
    {
      campaignName: 'SP - Genérica - Café Grãos & Prensa',
      adGroupName: 'Prensa Francesa',
      customerSearchTerm: 'prensa francesa 800ml vidro',
      targeting: 'prensa francesa',
      matchType: 'PHRASE',
      impressions: 22000,
      clicks: 520,
      spend: 1040.0,
      orders: 58,
      sales: 6954.0,
      ctr: 2.36,
      cpc: 2.0,
      acos: 14.95,
      roas: 6.69,
      conversionRate: 11.15,
    },
  ];

  // Advertised products
  const advertisedProducts = [
    {
      campaignName: 'SP - Brand Defense - Café Especial',
      sku: 'SKU-CAFE-ESPR-1KG',
      asin: 'B08ABC1234',
      impressions: 48500,
      clicks: 820,
      spend: 984.0,
      orders: 145,
      sales: 13050.0,
      acos: 7.54,
    },
    {
      campaignName: 'SP - Categoria - Moedores de Café',
      sku: 'SKU-MOED-ELETR-INOX',
      asin: 'B08XYZ5678',
      impressions: 89400,
      clicks: 1240,
      spend: 2976.0,
      orders: 88,
      sales: 16720.0,
      acos: 17.8,
    },
    {
      campaignName: 'SP - Genérica - Café Grãos & Prensa',
      sku: 'SKU-PREN-FRANC-800ML',
      asin: 'B09KLM9012',
      impressions: 68000,
      clicks: 940,
      spend: 1974.0,
      orders: 62,
      sales: 7434.0,
      acos: 26.55,
    },
    // SKU alert: Spent > 1x PMV without sale!
    {
      campaignName: 'SP - Concorrentes Diretos - Cafeteiras',
      sku: 'SKU-XIC-CERAM-SET4',
      asin: 'B09UIO2345',
      impressions: 12000,
      clicks: 74,
      spend: 185.0,
      orders: 0,
      sales: 0,
      acos: 0,
    },
  ];

  const auditFiles = [
    {
      id: 'demo-1',
      name: 'BusinessReport-08-2026-por-Data.csv',
      type: 'business_date' as const,
      typeLabel: 'Relatório Comercial por Data (Business Report)',
      rowCount: 30,
      dateMin: '2026-08-01',
      dateMax: '2026-08-30',
      extractionDate: '2026-09-01T08:00:00Z',
      delimiter: 'Vírgula (,)',
      encoding: 'UTF-8',
      detectedColumns: [
        'Data',
        'Vendas de produtos encomendados',
        'Unidades encomendadas',
        'Total de itens do pedido',
        'Sessões - Total',
        'Visualizações de página - Total',
        'Porcentagem da Buy Box (Caixa de compra)',
        'Porcentagem da sessão da unidade',
      ],
      missingCrucialColumns: [],
      status: 'valid' as const,
      statusMessage: 'Arquivo auditado e sem divergências estruturais.',
      granularity: 'Diária consolidada',
      officialUse: 'Fonte oficial de Faturamento Comercial, Sessões e Taxa de Conversão da Loja',
      limitations: 'Não discrimina pedidos B2B de forma isolada nem canais logísticos.',
    },
    {
      id: 'demo-2',
      name: 'BusinessReport-08-2026-por-ASIN-SKU.csv',
      type: 'business_sku' as const,
      typeLabel: 'Relatório Comercial por SKU/ASIN',
      rowCount: 7,
      delimiter: 'Vírgula (,)',
      encoding: 'UTF-8',
      detectedColumns: [
        'SKU',
        'ASIN filho',
        'Título',
        'Sessões - Total',
        'Visualizações de página - Total',
        'Porcentagem da Buy Box (Caixa de compra)',
        'Unidades encomendadas',
        'Vendas de produtos encomendados',
        'Porcentagem da sessão da unidade',
      ],
      missingCrucialColumns: [],
      status: 'valid' as const,
      statusMessage: 'Arquivo auditado com sucesso.',
      granularity: 'Por SKU / ASIN no período',
      officialUse: 'Análise de conversão, Pareto e tráfego por produto',
      limitations: 'Não contempla custos operacionais ou margem de contribuição.',
    },
    {
      id: 'demo-3',
      name: 'Todos_os_Pedidos_Amazon_08-2026.txt',
      type: 'orders_purchase_date' as const,
      typeLabel: 'Todos os Pedidos (Por Data do Pedido)',
      rowCount: 280,
      dateMin: '2026-08-01',
      dateMax: '2026-08-30',
      delimiter: 'TSV (Tabulação)',
      encoding: 'UTF-8',
      detectedColumns: [
        'amazon-order-id',
        'order-item-id',
        'purchase-date',
        'last-updated-date',
        'order-status',
        'fulfillment-channel',
        'sales-channel',
        'sku',
        'asin',
        'product-name',
        'quantity',
        'item-price',
        'ship-city',
        'ship-state',
      ],
      missingCrucialColumns: [],
      status: 'valid' as const,
      statusMessage: 'Deduplicado por amazon-order-id + order-item-id com sucesso.',
      granularity: 'Por item de pedido',
      officialUse: 'Detalhamento operacional de pedidos, logística (FBA vs FBM) e cidades',
      limitations: 'Contém pedidos pendentes e cancelados; não somar com o Relatório Comercial!',
    },
    {
      id: 'demo-4',
      name: 'AmazonAds_Campanhas_Agosto_2026.csv',
      type: 'ads_campaigns' as const,
      typeLabel: 'Amazon Ads — Campanhas',
      rowCount: 6,
      delimiter: 'Vírgula (,)',
      encoding: 'UTF-8',
      detectedColumns: [
        'Campaign Name',
        'Status',
        'Budget',
        'Impressions',
        'Clicks',
        'Spend',
        'Orders',
        'Sales',
        'CTR',
        'CPC',
        'ACOS',
        'ROAS',
      ],
      missingCrucialColumns: [],
      status: 'valid' as const,
      statusMessage: 'Fonte oficial de gasto consolidado validada.',
      granularity: 'Por campanha de publicidade',
      officialUse: 'FONTE OFICIAL DE GASTO E VENDAS ADS CONSOLIDADAS (evita duplicar com termos)',
      limitations: 'Janela de atribuição padrão Amazon de 7 a 14 dias.',
    },
    {
      id: 'demo-5',
      name: 'AmazonAds_Termos_de_Pesquisa_Agosto_2026.csv',
      type: 'ads_search_terms' as const,
      typeLabel: 'Amazon Ads — Termos de Pesquisa',
      rowCount: 7,
      delimiter: 'Vírgula (,)',
      encoding: 'UTF-8',
      detectedColumns: [
        'Campaign Name',
        'Ad Group Name',
        'Customer Search Term',
        'Targeting',
        'Match Type',
        'Impressions',
        'Clicks',
        'Spend',
        'Orders',
        'Sales',
      ],
      missingCrucialColumns: [],
      status: 'valid' as const,
      statusMessage: 'Identificados termos com 10-15 cliques e zero conversão.',
      granularity: 'Por termo de pesquisa digitado pelo cliente',
      officialUse: 'Auditoria de termos de busca e oportunidades de negativação',
      limitations: 'Não deve ser somado com o gasto de campanhas!',
    },
  ];

  return {
    sessionConfig: {
      accountName: 'Loja Exemplo (Demonstração)',
      timezone: 'America/Sao_Paulo',
      startDate: '2026-09-01',
      endDate: '2026-09-20',
      currency: 'BRL',
      primaryAdsSource: 'campaigns',
      recalculatedAt: new Date().toISOString(),
      consentSavePreferences: false,
    },
    businessDays,
    businessSkus,
    orders,
    campaigns,
    searchTerms,
    targets: [],
    advertisedProducts,
    cogsList: [],
    commissionPreview: [
      {
        sku: 'SKU-CAFE-ESPR-1KG',
        asin: 'B08ABC1234',
        precoPublicado: 90.0,
        comissaoEstimadaUnidade: 10.80,
        percentualComissaoEfetivo: 12.0,
        categoriaAmazon: 'Casa e Cozinha',
        comissaoMinima: 1.0,
      },
      {
        sku: 'SKU-MOED-ELETR-INOX',
        asin: 'B08XYZ5678',
        precoPublicado: 190.0,
        comissaoEstimadaUnidade: 24.70,
        percentualComissaoEfetivo: 13.0,
        categoriaAmazon: 'Beleza',
        comissaoMinima: 1.0,
      },
      {
        sku: 'SKU-PREN-FRANC-800ML',
        asin: 'B09KLM9012',
        precoPublicado: 120.0,
        comissaoEstimadaUnidade: 14.40,
        percentualComissaoEfetivo: 12.0,
        categoriaAmazon: 'Casa e Cozinha',
        comissaoMinima: 1.0,
      },
      {
        sku: 'SKU-CANEC-TERM-450ML',
        asin: 'B09QWE3456',
        precoPublicado: 80.0,
        comissaoEstimadaUnidade: 9.60,
        percentualComissaoEfetivo: 12.0,
        categoriaAmazon: 'Casa e Cozinha',
        comissaoMinima: 1.0,
      },
      {
        sku: 'SKU-FILTR-PAPEL-103',
        asin: 'B09RTY7890',
        precoPublicado: 35.0,
        comissaoEstimadaUnidade: 4.20,
        percentualComissaoEfetivo: 12.0,
        categoriaAmazon: 'Casa e Cozinha',
        comissaoMinima: 1.0,
      },
    ],
    rentabilidadeReal: [
      {
        sku: 'SKU-CAFE-ESPR-1KG',
        asin: 'B08ABC1234',
        nomeProduto: 'Café Especial em Grãos Torrado 1kg Gourmet 100% Arábica Cerrado Mineiro',
        marca: 'Cerrado Gourmet',
        receitaLiquidaTotal: 31230.0,
        receitaLiquidaUnitaria: 67.89,
        vendasBrutasTotal: 41354.0,
        vendasBrutasUnitaria: 89.9,
        precoMedioVenda: 89.9,
        unidadesCobradas: 460,
        unidadesVendidas: 460,
        unidadesReembolsadas: 12,
        unidadesLiquidasVendidas: 448,
        indiceDevolucao: 2.6,
        custoLogisticaTotal: 3105.0,
        custoLogisticaUnitario: 6.75,
        tarifaFbaTotal: 0,
        tarifaFbaUnitaria: 0,
        tarifaDbaTotal: 3105.0,
        tarifaDbaUnitaria: 6.75,
        comissaoTotal: 4962.48,
        comissaoUnitaria: 10.78,
        tarifaVendaTotal: 4962.48,
        tarifaVendaUnitaria: 10.78,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 80.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 250.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 1200.0,
        custoAdsUnitario: 2.61,
        custoAdsSponsoredProductsTotal: 1200.0,
        outrosAjustesTotal: 0,
        cogsTotal: 13800.0,
        cogsUnitario: 30.0,
        custoEmbalagemTotal: 460.0,
        custoEmbalagemUnitario: 1.0,
        impostosTotal: 2481.24,
        impostosUnitario: 5.39,
        custoAmazonTotal: 4962.48 + 3105.0 + 80.0 + 250.0 + 1200.0,
        resultadoAntesCogs: 31230.0 - 1200.0,
        lucroLiquidoEstimado: 31230.0 - 13800.0 - 460.0 - 2481.24,
        margemContribuicao: 72.6,
        margemLiquida: 35.0,
        breakEvenAcos: 48.2,
        statusConfiabilidade: 'concluido',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      },
      {
        sku: 'SKU-MOED-ELETR-INOX',
        asin: 'B08XYZ5678',
        nomeProduto: 'Moedor de Café Elétrico Automático Lâminas Inox 220V Bivolt Compacto',
        marca: 'MoedMax',
        receitaLiquidaTotal: 26150.0,
        receitaLiquidaUnitaria: 141.35,
        vendasBrutasTotal: 35150.0,
        vendasBrutasUnitaria: 190.0,
        precoMedioVenda: 190.0,
        unidadesCobradas: 185,
        unidadesVendidas: 185,
        unidadesReembolsadas: 8,
        unidadesLiquidasVendidas: 177,
        indiceDevolucao: 4.3,
        custoLogisticaTotal: 1665.0,
        custoLogisticaUnitario: 9.0,
        tarifaFbaTotal: 1665.0,
        tarifaFbaUnitaria: 9.0,
        tarifaDbaTotal: 0,
        tarifaDbaUnitaria: 0,
        comissaoTotal: 4569.5,
        comissaoUnitaria: 24.7,
        tarifaVendaTotal: 4569.5,
        tarifaVendaUnitaria: 24.7,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 120.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 410.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 2800.0,
        custoAdsUnitario: 15.13,
        custoAdsSponsoredProductsTotal: 2800.0,
        outrosAjustesTotal: 0,
        cogsTotal: 14800.0,
        cogsUnitario: 80.0,
        custoEmbalagemTotal: 370.0,
        custoEmbalagemUnitario: 2.0,
        impostosTotal: 2109.0,
        impostosUnitario: 11.4,
        custoAmazonTotal: 4569.5 + 1665.0 + 120.0 + 410.0 + 2800.0,
        resultadoAntesCogs: 26150.0 - 2800.0,
        lucroLiquidoEstimado: 26150.0 - 14800.0 - 370.0 - 2109.0,
        margemContribuicao: 66.4,
        margemLiquida: 25.2,
        breakEvenAcos: 41.5,
        statusConfiabilidade: 'concluido',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      },
      {
        sku: 'SKU-PREN-FRANC-800ML',
        asin: 'B09KLM9012',
        nomeProduto: 'Prensa Francesa Cafeteira de Vidro Borossilicato 800ml com Filtro Duplo',
        marca: 'CafféClass',
        receitaLiquidaTotal: 19120.0,
        receitaLiquidaUnitaria: 91.04,
        vendasBrutasTotal: 25179.0,
        vendasBrutasUnitaria: 119.9,
        precoMedioVenda: 119.9,
        unidadesCobradas: 210,
        unidadesVendidas: 210,
        unidadesReembolsadas: 4,
        unidadesLiquidasVendidas: 206,
        indiceDevolucao: 1.9,
        custoLogisticaTotal: 1417.5,
        custoLogisticaUnitario: 6.75,
        tarifaFbaTotal: 0,
        tarifaFbaUnitaria: 0,
        tarifaDbaTotal: 1417.5,
        tarifaDbaUnitaria: 6.75,
        comissaoTotal: 3021.48,
        comissaoUnitaria: 14.39,
        tarifaVendaTotal: 3021.48,
        tarifaVendaUnitaria: 14.39,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 50.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 120.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 950.0,
        custoAdsUnitario: 4.52,
        custoAdsSponsoredProductsTotal: 950.0,
        outrosAjustesTotal: 0,
        cogsTotal: 9450.0,
        cogsUnitario: 45.0,
        custoEmbalagemTotal: 210.0,
        custoEmbalagemUnitario: 1.0,
        impostosTotal: 1510.74,
        impostosUnitario: 7.19,
        custoAmazonTotal: 3021.48 + 1417.5 + 50.0 + 120.0 + 950.0,
        resultadoAntesCogs: 19120.0 - 950.0,
        lucroLiquidoEstimado: 19120.0 - 9450.0 - 210.0 - 1510.74,
        margemContribuicao: 72.1,
        margemLiquida: 31.5,
        breakEvenAcos: 46.2,
        statusConfiabilidade: 'concluido',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      },
      {
        sku: 'SKU-CANEC-TERM-450ML',
        asin: 'B09QWE3456',
        nomeProduto: 'Caneca Térmica Inox com Tampa Hermética 450ml Parede Dupla Vácuo',
        marca: 'ThermosPro',
        receitaLiquidaTotal: 8400.0,
        receitaLiquidaUnitaria: 60.0,
        vendasBrutasTotal: 11186.0,
        vendasBrutasUnitaria: 79.9,
        precoMedioVenda: 79.9,
        unidadesCobradas: 140,
        unidadesVendidas: 140,
        unidadesReembolsadas: 15,
        unidadesLiquidasVendidas: 125,
        indiceDevolucao: 10.7,
        custoLogisticaTotal: 945.0,
        custoLogisticaUnitario: 6.75,
        tarifaFbaTotal: 0,
        tarifaFbaUnitaria: 0,
        tarifaDbaTotal: 945.0,
        tarifaDbaUnitaria: 6.75,
        comissaoTotal: 1342.32,
        comissaoUnitaria: 9.59,
        tarifaVendaTotal: 1342.32,
        tarifaVendaUnitaria: 9.59,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 40.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 450.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 1500.0,
        custoAdsUnitario: 10.71,
        custoAdsSponsoredProductsTotal: 1500.0,
        outrosAjustesTotal: 0,
        cogsTotal: 4900.0,
        cogsUnitario: 35.0,
        custoEmbalagemTotal: 140.0,
        custoEmbalagemUnitario: 1.0,
        impostosTotal: 671.16,
        impostosUnitario: 4.79,
        custoAmazonTotal: 1342.32 + 945.0 + 40.0 + 450.0 + 1500.0,
        resultadoAntesCogs: 8400.0 - 1500.0,
        lucroLiquidoEstimado: 8400.0 - 4900.0 - 140.0 - 671.16,
        margemContribuicao: 61.6,
        margemLiquida: 24.0,
        breakEvenAcos: 29.5,
        statusConfiabilidade: 'concluido',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      },
      {
        sku: 'SKU-FILTR-PAPEL-103',
        asin: 'B09RTY7890',
        nomeProduto: 'Kit 4 Caixas Filtro de Papel para Café N° 103 Orgânico Biodegradável',
        marca: 'Cerrado Gourmet',
        receitaLiquidaTotal: 8120.0,
        receitaLiquidaUnitaria: 25.37,
        vendasBrutasTotal: 11200.0,
        vendasBrutasUnitaria: 35.0,
        precoMedioVenda: 35.0,
        unidadesCobradas: 320,
        unidadesVendidas: 320,
        unidadesReembolsadas: 2,
        unidadesLiquidasVendidas: 318,
        indiceDevolucao: 0.6,
        custoLogisticaTotal: 1440.0,
        custoLogisticaUnitario: 4.5,
        tarifaFbaTotal: 0,
        tarifaFbaUnitaria: 0,
        tarifaDbaTotal: 1440.0,
        tarifaDbaUnitaria: 4.5,
        comissaoTotal: 1344.0,
        comissaoUnitaria: 4.2,
        tarifaVendaTotal: 1344.0,
        tarifaVendaUnitaria: 4.2,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 20.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 40.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 300.0,
        custoAdsUnitario: 0.94,
        custoAdsSponsoredProductsTotal: 300.0,
        outrosAjustesTotal: 0,
        cogsTotal: 4800.0,
        cogsUnitario: 15.0,
        custoEmbalagemTotal: 320.0,
        custoEmbalagemUnitario: 1.0,
        impostosTotal: 672.0,
        impostosUnitario: 2.1,
        custoAmazonTotal: 1344.0 + 1440.0 + 20.0 + 40.0 + 300.0,
        resultadoAntesCogs: 8120.0 - 300.0,
        lucroLiquidoEstimado: 8120.0 - 4800.0 - 320.0 - 672.0,
        margemContribuicao: 69.8,
        margemLiquida: 20.7,
        breakEvenAcos: 32.5,
        statusConfiabilidade: 'concluido',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      },
      {
        sku: 'SKU-XIC-CERAM-SET4',
        asin: 'B09UIO2345',
        nomeProduto: 'Conjunto 4 Xícaras de Café Expresso Cerâmica Artesanal 80ml',
        marca: 'Cerrado Gourmet',
        receitaLiquidaTotal: 2950.0,
        receitaLiquidaUnitaria: 65.55,
        vendasBrutasTotal: 4045.5,
        vendasBrutasUnitaria: 89.9,
        precoMedioVenda: 89.9,
        unidadesCobradas: 45,
        unidadesVendidas: 45,
        unidadesReembolsadas: 5,
        unidadesLiquidasVendidas: 40,
        indiceDevolucao: 11.1,
        custoLogisticaTotal: 303.75,
        custoLogisticaUnitario: 6.75,
        tarifaFbaTotal: 0,
        tarifaFbaUnitaria: 0,
        tarifaDbaTotal: 303.75,
        tarifaDbaUnitaria: 6.75,
        comissaoTotal: 485.46,
        comissaoUnitaria: 10.78,
        tarifaVendaTotal: 485.46,
        tarifaVendaUnitaria: 10.78,
        tarifaItemTotal: 0,
        tarifaArmazenagemTotal: 15.0,
        tarifaBaixoInventarioTotal: 0,
        tarifaRemocaoTotal: 0,
        tarifaDescarteTotal: 0,
        tarifaReembolsoTotal: 150.0,
        tarifaCupomTotal: 0,
        tarifaPromocaoTotal: 0,
        custoAdsTotal: 1150.0,
        custoAdsUnitario: 25.55,
        custoAdsSponsoredProductsTotal: 1150.0,
        outrosAjustesTotal: 0,
        cogsTotal: 0,
        cogsUnitario: 0,
        custoEmbalagemTotal: 0,
        custoEmbalagemUnitario: 0,
        impostosTotal: 242.73,
        impostosUnitario: 5.39,
        custoAmazonTotal: 485.46 + 303.75 + 15.0 + 150.0 + 1150.0,
        resultadoAntesCogs: 2950.0 - 1150.0,
        lucroLiquidoEstimado: 0,
        margemContribuicao: 44.4,
        margemLiquida: 0,
        breakEvenAcos: null,
        statusConfiabilidade: 'pendente_cogs',
        arquivoOrigem: 'report_rentabilidade_setembro_2026.xlsx',
        periodoInicio: '2026-09-01',
        periodoFim: '2026-09-30'
      }
    ],
    auditFiles,
  };
}
